//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crm1Entities : DbContext
    {
        public crm1Entities()
            : base("name=crm1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_brand> t_brand { get; set; }
        public virtual DbSet<t_brand_businessformat> t_brand_businessformat { get; set; }
        public virtual DbSet<t_brand_product> t_brand_product { get; set; }
        public virtual DbSet<t_synonym> t_synonym { get; set; }
        public virtual DbSet<t_word> t_word { get; set; }
        public virtual DbSet<t_word_synonym> t_word_synonym { get; set; }
        public virtual DbSet<test_table> test_table { get; set; }
        public virtual DbSet<test_table2> test_table2 { get; set; }
        public virtual DbSet<t_basic_info> t_basic_info { get; set; }
        public virtual DbSet<t_activity> t_activity { get; set; }
    }
}
