//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_activity
    {
        public int id { get; set; }
        public string code { get; set; }
        public string activity { get; set; }
        public string floor { get; set; }
        public string basic_info { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> begin { get; set; }
        public Nullable<System.DateTime> end { get; set; }
    }
}
