//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_brand_product
    {
        public int id { get; set; }
        public string brand_code { get; set; }
        public string product_word_code { get; set; }
    }
}
